todo/config/routes.rb
Todo::Application.routes.draw do |map|
  devise_for :users, :path_names => { :sign_up => "register" }

  resources :projects, :tasks
  root :to => "projects#index"
  

end

todo/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
end

todo/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

todo/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

todo/app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => '9ae178eac1fbbd4062a93c8c558a12ef'
  
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password"). 
  # filter_parameter_logging :password
end

todo/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    @projects = Project.find(:all)
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Successfully created project."
      redirect_to @project
    else
      render :action => 'new'
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Successfully updated project."
      redirect_to @project
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Successfully destroyed project."
    redirect_to projects_url
  end
end

todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new(:project_id => params[:project_id])
  end
  
  def create
    @task = Task.new(params[:task])
    if @task.save
      flash[:notice] = "Successfully created task."
      redirect_to @task.project
    else
      render :action => 'new'
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      flash[:notice] = "Successfully updated task."
      redirect_to @task.project
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Successfully destroyed task."
    redirect_to @task.project
  end
end

todo/app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

todo/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

todo/app/helpers/projects_helper.rb
module ProjectsHelper
end

todo/app/helpers/tasks_helper.rb
module TasksHelper
end

todo/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
      </div>
      
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      
      <% if show_title? %>
        <h1><%= yield(:title) %></h1>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

todo/app/views/projects/_form.html.erb
<%= error_messages_for :project %>
<%= form_for @project do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

todo/app/views/projects/edit.html.erb
<% title "Edit Project" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @project %> |
  <%= link_to "View All", projects_path %>
</p>

todo/app/views/projects/index.html.erb
<% title "Projects" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for project in @projects %>
    <tr>
      <td><%= link_to project.name, project %></td>
      <td><%= link_to "Edit", edit_project_path(project) %></td>
      <td><%= link_to "Destroy", project, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Project", new_project_path %></p>

todo/app/views/projects/new.html.erb
<% title "New Project" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", projects_path %></p>

todo/app/views/projects/show.html.erb
<% title @project.name %>

<h2>Tasks</h2>
<ul>
  <% for task in @project.tasks %>
    <li>
      <%= task.name %>
      (<%= link_to "Edit", edit_task_path(task) %> |
      <%= link_to "Destroy", task, :confirm => "Are you sure?", :method => :delete %>)
    </li>
  <% end %>
</ul>

<p>
  <%= link_to "New Task", new_task_path(:project_id => @project) %> |
  <%= link_to "View All Projects", projects_path %>
</p>

todo/app/views/tasks/_form.html.erb
<%= error_messages_for :task %>
<%= form_for @task do |f| %>
  <%= f.hidden_field :project_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :completed_at %><br />
    <%= f.date_select :completed_at %>
  </p>
  <p><%= f.submit %></p>
<% end %>

todo/app/views/tasks/edit.html.erb
<% title "Edit Task" %>

<%= render :partial => 'form' %>

todo/app/views/tasks/new.html.erb
<% title "New Task" %>

<%= render :partial => 'form' %>